# Generated by Django 3.2.5 on 2021-07-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
